import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const out = "/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/outputs/california_transmission_project_timeline_simple.xlsx";
const tpr = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/tpr_standardized.json", "utf8"));
const tdf = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/tdf_historical.json", "utf8"));
const plan2008 = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2008_plan_previously_approved.json", "utf8"));
const plan2009Proposals = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2009_request_window_proposals.json", "utf8"));
const plan2006 = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2006_operating_guide_excerpt.json", "utf8"));
const plan2007Tehachapi = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2007_tehachapi_plan_project_history.json", "utf8"));
const plan2007TehachapiBoard = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_csrtp_2006_tehachapi_board_presentation_project_history.json", "utf8"));
const tehachapiLifecycle = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/tehachapi_lifecycle_primary_records.json", "utf8"));
const plan2010Briefing = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2010_plan_briefing_project_history.json", "utf8"));
const plan2010_2011 = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2010_2011_plan_project_history.json", "utf8"));
const plan2011_2012 = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_2011_2012_plan_project_history.json", "utf8"));
const laterPlanSpecs=[...Array.from({length:8},(_,index)=>{const start=2012+index;return {start,date:`${start+1}-03-${[20,25,27,28,17,22,29,25][index]}`};}),{start:2020,date:"2021-03-24"},{start:2021,date:"2022-03-17"},{start:2022,date:"2023-05-18"},{start:2023,date:"2024-05-23"},{start:2024,date:"2025-05-22"},{start:2025,date:"2026-05-19"}];
const laterPlans = await Promise.all(laterPlanSpecs.map(async({start,date})=>({period:`${start}/${start+1}`,date,data:JSON.parse(await fs.readFile(`/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_${start}_${start+1}_plan_project_history.json`,"utf8"))})));
const crosswalk = JSON.parse(await fs.readFile("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/03_Processed Data/caiso_annual_plan_crosswalk.json", "utf8"));
const proposalCrosswalkReview=crosswalk.proposal_snapshot_review??{reviewed_proposals:0,linked:0,unresolved:0};
const C={navy:"#123047",teal:"#0F766E",mint:"#E6F4F1",gold:"#FDF4D7",coral:"#FDE8E7",lavender:"#EEE9FA",line:"#D4DEE5",text:"#172B3A",white:"#FFFFFF"};
const asDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value??"")?new Date(`${value}T00:00:00Z`):null;
const blank=value=>value??"";
const grain=row=>/\b(program|blanket|bucket|placeholder|capital tools|misc\. contracts)\b/i.test(`${row.project_name??""} ${row.project_description??""}`)?"Review — program/bucket":"Project line item";
function title(sheet,label,context,last){sheet.getRange(`A1:${last}1`).merge();sheet.getRange("A1").values=[[label]];sheet.getRange("A1").format={fill:C.navy,font:{bold:true,color:C.white,size:16},verticalAlignment:"center"};sheet.getRange("A1").format.rowHeight=28;sheet.getRange(`A2:${last}2`).merge();sheet.getRange("A2").values=[[context]];sheet.getRange("A2").format={fill:C.mint,font:{italic:true,color:C.text,size:10},wrapText:true,verticalAlignment:"center"};sheet.getRange("A2").format.rowHeight=26;sheet.showGridLines=false;}
function header(sheet,range){sheet.getRange(range).format={fill:C.teal,font:{bold:true,color:C.white,size:9},wrapText:true,horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.teal}};sheet.getRange(range).format.rowHeight=32;}
function body(sheet,range){sheet.getRange(range).format={font:{color:C.text,size:9},wrapText:true,verticalAlignment:"top",borders:{insideHorizontal:{style:"thin",color:C.line}}};}
function makeTable(sheet,range,name){sheet.tables.add(range,true,name);sheet.freezePanes.freezeRows(4);}

const eventsByDate=new Map();
for(const e of tpr.events){const key=`${e.project_key}|${e.event_date}`;eventsByDate.set(key,[...(eventsByDate.get(key)??[]),e]);}
const signal=(projectKey,date)=>{const es=eventsByDate.get(`${projectKey}|${date}`)??[];return es.length?[...new Set(es.map(e=>`${e.event_category}: ${e.event_type}`))].join("; "):"No change signal in this report";};
const latest=new Map(tpr.latest_projects.map(r=>[r.project_key,`${r.snapshot_date}|${r.source_locator}`]));
const annualPlanRows=(plan,period,date)=>plan.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:"CAISO annual plan",key:`CAISO-TPP-${period.replace("/","-")}|${r.table}|${r.table_row}`,period:`${period} CAISO Plan`,observation_date:date,status:r.status,approval:blank(r.approval)||(r.status.startsWith("Found to be needed")?"Found needed in Board-approved plan":""),initial_isd:"",reported_isd:blank(r.target_isd),location:blank(r.service_area),path:"",length:null,voltage:null,capacity:"",signal:r.status,available:`${period} final plan: previously-approved rows report status/expected ISD; projects found needed report cost, service area, and expected ISD where stated. Cost handling: ${r.cost_method}; exact source cost is in Source locator.`,eligibility:"CAISO annual-plan project row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const annualPlanExcerptRows=plan2006.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:"CAISO annual plan",key:`CAISO-TPP-2006|${r.table}|${r.table_row}`,period:"2006 CAISO Plan — Operating Guide excerpt",observation_date:plan2006.source.presentation_date,status:r.status,approval:"",initial_isd:"",reported_isd:blank(r.target_isd),location:blank(r.region),path:[r.scope&&`Scope: ${r.scope}`,r.system_impact&&`System impact: ${r.system_impact}`].filter(Boolean).join(" | "),length:null,voltage:null,capacity:blank(r.capacity),signal:r.status,available:"2006 plan Board-presentation excerpt: scope, system impact, target ISD, and MVA capacity where stated. It displays 12 rows, not the complete 2006 plan; cost is not reported.",eligibility:"CAISO annual-plan excerpt row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const plan2007TehachapiRows=plan2007Tehachapi.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:"CAISO planning report",key:`CAISO-RENEW-2007-TEHACHAPI|${r.table}|${r.table_row}`,period:"2007 Renewables Integration Report — Tehachapi plan of service (partial)",observation_date:plan2007Tehachapi.source.report_date,status:r.status,approval:r.approval,initial_isd:"",reported_isd:blank(r.target_isd),location:"Tehachapi Wind Resource Area / SCE",path:blank(r.path_scope),length:r.length_miles??null,voltage:r.voltage_kv??null,capacity:blank(r.capacity),signal:r.status,available:`2007 CAISO planning report: one Tehachapi aggregate and 14 planned facilities from Appendix G, Table 1. Planned dates are not actual completion. Cost handling: ${r.cost_method}; exact source cost is in Source locator.`,eligibility:"CAISO planning-report project row — partial Tehachapi baseline",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const plan2007TehachapiBoardRows=plan2007TehachapiBoard.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:"CAISO Board presentation",key:`CAISO-CSRTP-2006-TEHACHAPI-BOARD-2007-01-24|${r.table}|${r.table_row}`,period:"2007 CSRTP-2006 Board presentation — Tehachapi recommendation (partial)",observation_date:plan2007TehachapiBoard.source.report_date,status:r.status,approval:r.approval,initial_isd:"",reported_isd:blank(r.target_isd),location:"Tehachapi Wind Resource Area / SCE",path:blank(r.path_scope),length:r.length_miles??null,voltage:r.voltage_kv??null,capacity:blank(r.capacity),signal:r.status,available:"January 2007 CAISO Board presentation: one Tehachapi management recommendation and 14 planned facilities from Slide 8. Planned ISDs are not actual completion. The presentation reports no project-level costs and does not establish Board approval.",eligibility:"CAISO Board-presentation project row — pre-approval plan snapshot",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const tehachapiLifecycleRows=tehachapiLifecycle.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:tehachapiLifecycle.sources.find(s=>s.source_id===r.source_id)?.source_stream??"Primary project source",key:r.project_key,period:r.period,observation_date:r.observation_date,status:r.status,approval:blank(r.approval),initial_isd:"",reported_isd:blank(r.reported_isd),location:blank(r.location),path:blank(r.path_scope),length:r.length_miles??null,voltage:r.voltage_kv??null,capacity:blank(r.capacity),signal:r.status,available:`Primary Tehachapi lifecycle source. ${r.cost_method} Exact source evidence is retained in Source locator.`,eligibility:"Project-level lifecycle observation",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,reported_cost_year:r.cost_year??null,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const plan2010BriefingRows=plan2010Briefing.records.map(r=>({project_name:blank(r.project_name),utility:blank(r.utility),stream:"CAISO annual plan",key:`CAISO-TPP-2010-BRIEFING|${r.table}|${r.table_row}`,period:"2010 CAISO Plan — Board briefing (partial)",observation_date:plan2010Briefing.source.presentation_date,status:r.status,approval:r.approval,initial_isd:"",reported_isd:"",location:"",path:"",length:null,voltage:null,capacity:"",signal:r.status,available:"2010 plan Board briefing: names two Board-approved reliability projects. Slide 7 reports only 29-project and utility-level aggregates; it does not supply individual project cost, route, scope, or schedule values.",eligibility:"CAISO annual-plan briefing row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const plan2008Row=r=>{const decision=blank(r.decision_status)||"Previously approved project status";const shortTerm=decision==="CAISO short-term-plan recommendation (not an approval)";const approval=decision==="CAISO management approved proposal"?"CAISO management approved":decision==="Proposal requiring CAISO Board approval"?"Requires CAISO Board approval":decision==="Not approved by CAISO management"?"Not approved":decision==="CAISO review in progress"?"Review in progress":"";const eligibility=shortTerm?"CAISO annual-plan short-term recommendation (not approval)":decision==="Not approved by CAISO management"||decision==="CAISO review in progress"?"CAISO annual-plan proposal row (not approved / in review)":"CAISO annual-plan project row";const available=shortTerm?"2008 short-term-plan recommendation: source-reported need, recommendation, and status where stated; no source cost or route/configuration detail.":`2008 plan: ${decision}. Cost handling: ${r.cost_method}; exact source cost is in Source locator.`;return {project_name:blank(r.project_name),utility:r.utility,stream:"CAISO annual plan",key:`CAISO-TPP-2008|${r.table.replace(/\\s+/g,"")}|${r.table_row}`,period:"2008 CAISO Plan",observation_date:"2008-01-28",status:r.note?`${decision} — ${r.note}`:decision,approval,initial_isd:"",reported_isd:blank(r.target_isd),location:blank(r.location),path:[r.path_scope&&`Scope: ${r.path_scope}`,r.purpose&&`Purpose / benefit: ${r.purpose}`].filter(Boolean).join(" | "),length:null,voltage:null,capacity:"",signal:r.note?`Status note: ${r.note}`:decision,available,eligibility,latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null};};
const plan2009ProposalRows=plan2009Proposals.records.map(r=>({project_name:r.project_name,utility:"CAISO",stream:"CAISO proposal snapshot",key:`CAISO-TPP-2009-PROP|${r.proposal_number}`,period:"2009 Request Window proposal snapshot",observation_date:plan2009Proposals.source.presentation_date,status:r.status,approval:"Proposal only — no final approval inferred",initial_isd:"",reported_isd:r.proposed_online_date,location:"",path:r.project_category,length:null,voltage:null,capacity:"",signal:r.status,available:"Project name, category/purpose, and proposed online date only; no cost or actual route/configuration.",eligibility:"CAISO 2009 request-window proposal (not a final plan approval)",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:null,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null}));
const rows=[
  ...tpr.snapshots.map(r=>({project_name:blank(r.project_name),utility:r.utility,stream:"Utility TPR",key:r.project_key,period:r.snapshot_date,observation_date:r.snapshot_date,status:blank(r.project_status),approval:r.caiso_approval_year??"",initial_isd:blank(r.original_isd),reported_isd:blank(r.current_isd),location:blank(r.location),path:blank(r.project_description),length:r.length_miles,voltage:r.voltage_kv,capacity:blank(r.capacity),signal:signal(r.project_key,r.snapshot_date),available:"Cost, schedule, path and size fields when reported",eligibility:grain(r),latest:latest.get(r.project_key)===`${r.snapshot_date}|${r.source_locator}`?"Yes":"No",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.current_total_cost_k,initial_cost_k:r.original_cost_midpoint_k,initial_isd_date:r.original_isd,reported_isd_date:r.current_isd})),
  ...tdf.observations.map(r=>({project_name:blank(r.project_name),utility:r.utility,stream:"CAISO TDF",key:r.project_key,period:r.period_label,observation_date:r.observation_date,status:blank(r.project_status??r.project_status_2023q2),approval:blank(r.approval_cycle),initial_isd:blank(r.original_isd),reported_isd:blank(r.observed_isd),location:"",path:"",length:null,voltage:null,capacity:"",signal:r.note==="In-Service"?"Status: in service":"Schedule/status observation",available:"Schedule and status only in this report; no cost/path/size field",eligibility:"CAISO TDF project row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:null,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null})),
  ...annualPlanExcerptRows,
  ...plan2007TehachapiBoardRows,
  ...plan2007TehachapiRows,
  ...tehachapiLifecycleRows,
  ...plan2010BriefingRows,
  ...plan2008.records.map(plan2008Row),
  ...plan2009ProposalRows,
  ...plan2010_2011.records.map(r=>({project_name:blank(r.project_name),utility:r.utility,stream:"CAISO annual plan",key:`CAISO-TPP-2010-2011|${r.table.replace(/\\s+/g,"")}|${r.table_row}`,period:"2010/2011 CAISO Plan",observation_date:"2011-05-18",status:r.status,approval:r.table==="Table 8.2-2"?"Recommended for Board approval":"",initial_isd:"",reported_isd:blank(r.target_isd),location:blank(r.service_area),path:[r.path_scope&&`Scope: ${r.path_scope}`].filter(Boolean).join(" | "),length:null,voltage:null,capacity:blank(r.capacity),signal:r.status,available:`2010/11 plan: status and target ISD for previously approved rows; cost, service area, and target ISD for new reliability rows where reported. Cost handling: ${r.cost_method}; exact source cost is in Source locator.`,eligibility:"CAISO annual-plan project row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null})),
  ...plan2011_2012.records.map(r=>({project_name:blank(r.project_name),utility:r.utility,stream:"CAISO annual plan",key:`CAISO-TPP-2011-2012|${r.table.replace(/\\s+/g,"")}|${r.table_row}`,period:"2011/2012 CAISO Plan",observation_date:"2012-03-14",status:r.status,approval:"",initial_isd:"",reported_isd:blank(r.target_isd),location:blank(r.service_area),path:[r.submission_type&&`Submission type: ${r.submission_type}`].filter(Boolean).join(" | "),length:null,voltage:null,capacity:"",signal:r.status,available:`2011/12 plan: status and expected ISD for previously approved rows; cost, service area, and in-service date for new reliability rows where reported. Cost handling: ${r.cost_method}; exact source cost is in Source locator.`,eligibility:"CAISO annual-plan project row",latest:"n.a.",source_id:r.source_id,locator:r.source_locator,url:r.source_url,title:r.source_title,current_cost_k:r.cost_value_k,initial_cost_k:null,initial_isd_date:null,reported_isd_date:null})),
  ...laterPlans.flatMap(plan=>annualPlanRows(plan.data,plan.period,plan.date))
].sort((a,b)=>`${a.observation_date}|${a.project_name}`.localeCompare(`${b.observation_date}|${b.project_name}`));

const crosswalksByProjectKey=new Map();
for(const link of crosswalk.records){for(const key of link.project_keys??[])crosswalksByProjectKey.set(key,[...(crosswalksByProjectKey.get(key)??[]),link]);}
for(const row of rows){const links=crosswalksByProjectKey.get(row.key)??[];row.crosswalk_id=links.map(link=>link.crosswalk_id).join(" | ");row.crosswalk_method=[...new Set(links.map(link=>link.match_method))].join(" | ");row.crosswalk_confidence=[...new Set(links.map(link=>link.confidence))].join(" | ");row.crosswalk_evidence=links.map(link=>`${link.crosswalk_id}: ${link.match_rationale} ${link.evidence}`).join(" || ");}

const cpi=[
  [2002,77.214],[2003,78.967],[2004,81.081],[2005,83.832],[2006,86.536],[2007,89.004],[2008,92.422],[2009,92.093],[2010,93.603],[2011,96.558],[2012,98.556],[2013,100.000],[2014,101.622],[2015,101.743],[2016,103.027],[2017,105.221],[2018,107.791],[2019,109.745],[2020,111.098],[2021,116.318],[2022,125.626],[2023,130.797],[2024,134.655],[2025,138.289]
];

const wb=Workbook.create();
const dashboard=wb.worksheets.add("Dashboard");
const history=wb.worksheets.add("Project History");
const sourceRegistry=wb.worksheets.add("Source Registry");
const coverage=wb.worksheets.add("Coverage");
const inflation=wb.worksheets.add("Inflation");

title(dashboard,"California Transmission Project History","One project-history table, a citation and coverage register, and an inflation reference for cost comparisons.","H");
dashboard.getRange("A4:H4").merge();dashboard.getRange("A4").values=[["What each tab means"]];dashboard.getRange("A4").format={fill:C.teal,font:{bold:true,color:C.white,size:11}};
const tabs=[["Dashboard","Read this first. It explains what the history contains, how each source reports it, the cost-price-year method, and the interpretation limits."],["Project History","The working table. Filter Project ID within a source stream, or Crosswalk ID for reviewed CAISO plan links; then sort Observation date oldest to newest. Supporting audit fields are hidden to the right, not deleted."],["Source Registry","Direct URLs, source IDs, and the locator method used for every project-history row."],["Coverage","The year-by-year map of what is imported, found but not yet extracted, or still missing."],["Inflation","Annual CPI-U comparison factors. Change the comparison-dollar year here; Project History updates its real-dollar cost fields."]];
dashboard.getRange("A6:B6").values=[["Tab","Use it for"]];header(dashboard,"A6:B6");dashboard.getRange("A7:B11").values=tabs;body(dashboard,"A7:B11");dashboard.getRange("A:A").format.columnWidth=25;dashboard.getRange("B:B").format.columnWidth=112;dashboard.getRange("A7:B11").format.rowHeight=38;
const end=rows.length+4;
dashboard.getRange("D6:F6").values=[["Metric","Value","Meaning"]];header(dashboard,"D6:F6");dashboard.getRange("D7:F13").values=[["All project observations",null,"Each source report is retained as a separate row."],["CAISO plan / related observations",null,"12 rows from a 2006 excerpt; 15 January 2007 pre-approval Board-presentation observations; 15 September 2007 Tehachapi planning-report observations; two named project observations from a partial 2010 briefing; 2008 Tables 3-1–3-13; 2010/11; and Board-approved final plan cycles from 2011/12 through 2025/26. The 36 short-term-plan rows are recommendations, not approvals."],["CAISO proposal snapshot observations",null,"14 cited 2009 request-window proposals. They are not final approvals and have no cost or actual route data."],["Utility TPR observations",null,"2024–26 public utility project records; most cost/path/size fields are here."],["CAISO TDF observations",null,"2020/21–July 2026 schedule/status history; no cost/path/size fields."],["Latest utility project rows",null,"Filter Latest utility row? = Yes for one current row per stable utility project ID."],["Cost observations with 2025-dollar factor",null,"Reported cost rows with a complete annual CPI-U comparison factor."]];
dashboard.getRange("E7:E13").formulas=[[`=COUNTA('Project History'!A5:A${end})`],[`=COUNTIFS('Project History'!C5:C${end},"CAISO annual plan")+COUNTIFS('Project History'!C5:C${end},"CAISO planning report")+COUNTIFS('Project History'!C5:C${end},"CAISO Board presentation")`],[`=COUNTIFS('Project History'!C5:C${end},"CAISO proposal snapshot")`],[`=COUNTIFS('Project History'!C5:C${end},"Utility TPR")`],[`=COUNTIFS('Project History'!C5:C${end},"CAISO TDF")`],[`=COUNTIFS('Project History'!AB5:AB${end},"Yes")`],[`=COUNTIFS('Project History'!K5:K${end},">0")`]];body(dashboard,"D7:F13");dashboard.getRange("E7:E13").format={fill:C.gold,font:{bold:true},horizontalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};dashboard.getRange("D:D").format.columnWidth=32;dashboard.getRange("E:E").format.columnWidth=18;dashboard.getRange("F:F").format.columnWidth=60;
dashboard.getRange("A14:H14").merge();dashboard.getRange("A14").values=[["What Project History provides and how"]];dashboard.getRange("A14").format={fill:C.navy,font:{bold:true,color:C.white,size:11}};
const dictionary=[["Data group","What is provided","How it is reported / caveat"],["Identity and timing","Project name, source-specific Project ID, utility/PTO, report period, observation date, status, approval cycle/year.",`Filter Project ID to see a project's retained report history, then sort Observation date. IDs are stable within their source stream; CAISO annual-plan, Board-presentation, planning-report, TDF, utility TPR, and primary-project sources are separate systems and should not be joined without a documented crosswalk. The 2009 proposal review links only ${proposalCrosswalkReview.linked} of ${proposalCrosswalkReview.reviewed_proposals} proposals; ${proposalCrosswalkReview.unresolved} remain intentionally unlinked.`],["Cost","Reported and initial costs in nominal $M; a dollar year beside each cost; and selected-year CPI-U comparison costs/differences.","Utility TPR source costs are in $000 and are converted to $M. CAISO plan ranges display as midpoints, '<' values as their stated ceiling, and $0 as reported; the September 2007 Tehachapi $1.8B is an unallocated aggregate. The Tehachapi CPUC/SCE lifecycle rows use a stated source dollar year where the source provides one; other sources use a report-year proxy. Exact source text is retained in Source locator."],["Schedule","Initial and reported/actual in-service dates; schedule shift where both date values are supplied.","The January Board presentation and September 2007 Tehachapi report preserve planned component ISDs, not actual completion. The Tehachapi lifecycle adds CPUC and SCE status milestones, including SCE’s segment-completion timeline. The 2008, 2010/11, and 2011/12–2025/26 final plans provide planned, target, or expected ISDs for cited project rows. Status tables record completed, cancelled, and some source-described replacements/re-scopes. The 2025/26 recommendation tables do not report an ISD, so their schedule field is blank. CAISO TDF has schedule/status observations. Utility TPR adds original and current/actual dates when reported."],["Path and size","Location, narrative path/scope, line length, voltage, and capacity.","The September 2007 Tehachapi report provides Appendix G Table 1 component scope/size where stated; the primary Tehachapi lifecycle adds CPUC routing/undergrounding and SCE completion evidence. Annual-plan rows carry only fields reported in their table: 2008 has PG&E scope/purpose; 2010/11 onward new-needed rows have service area. Utility TPR adds most other path and size fields. A blank means the source did not report it, not zero or no change."],["Change and evidence","Change signal, eligibility, latest utility record flag, source ID, locator, direct URL, title.","Change signals are automated comparisons or reported statuses. They are research flags, not confirmation of a reroute, cancellation, or cost overrun."]];
dashboard.getRange("A15:C15").values=[dictionary[0]];header(dashboard,"A15:C15");dashboard.getRange("A16:C20").values=dictionary.slice(1);body(dashboard,"A16:C20");dashboard.getRange("A:A").format.columnWidth=25;dashboard.getRange("B:B").format.columnWidth=70;dashboard.getRange("C:C").format.columnWidth=83;dashboard.getRange("A16:C20").format.rowHeight=43;
dashboard.getRange("A22:H22").merge();dashboard.getRange("A22").values=[["Cost comparison method"]];dashboard.getRange("A22").format={fill:C.teal,font:{bold:true,color:C.white,size:11}};
dashboard.getRange("A23:H25").merge();dashboard.getRange("A23").values=[["Each nominal cost is paired with a dollar-year field and source evidence (Source ID, locator, and URL) in Project History. The comparison year is editable in Inflation; the live calculated-cost and cost-change labels immediately above the table headers update to that selected year. CPI-U is a general-inflation baseline, not a construction-cost index, so use it for a transparent sensitivity check rather than as the final engineering escalation method. 2026 values remain nominal until a full-year CPI-U is available."]];dashboard.getRange("A23").format={fill:C.coral,font:{color:C.text,size:10},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};
dashboard.getRange("A27:H27").merge();dashboard.getRange("A27").values=[["Coverage"]];dashboard.getRange("A27").format={fill:C.teal,font:{bold:true,color:C.white,size:11}};
dashboard.getRange("A28:H30").merge();dashboard.getRange("A28").values=[["CAISO coverage includes a 12-row 2006 excerpt, 15 January 2007 pre-approval Board-presentation observations, 15 September 2007 Tehachapi planning-report observations, two named 2010 Board-briefing projects, 2008 Tables 3-1–3-13, 2010/11, and final plan cycles from 2011/12 through 2025/26. The Tehachapi lifecycle is also expanded with CPUC CPCN, undergrounding, cost-cap, and SCE completion/cost-filing evidence. The two 2007 snapshots retain the same planned facilities as separate source evidence: January records a management recommendation, September reports approval retrospectively. January has no costs; September's $1.8B is an unallocated aggregate; neither set of planned dates is actual completion. See Coverage for year-level limits. Plan-cycle labels are never converted into calendar-year observations."]];dashboard.getRange("A28").format={fill:C.mint,font:{color:C.text,size:10},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};
dashboard.getRange("A32:H32").merge();dashboard.getRange("A32").values=[["Why project names repeat"]];dashboard.getRange("A32").format={fill:C.teal,font:{bold:true,color:C.white,size:11}};
dashboard.getRange("A33:H35").merge();dashboard.getRange("A33").values=[[`Yes—Project History intentionally keeps multiple observations when the same project appears in more than one source report period. A new row does not, by itself, mean the scope changed: it may simply be a recurring quarterly, annual, or utility TPR report. A crosswalk is the documented bridge between names/IDs in different source periods that represent the same project. For the conservative CAISO crosswalk links, filter Crosswalk ID, sort Observation date oldest to newest, and read Crosswalk evidence. A row can carry two link IDs when it bridges adjacent plan pairs. For the 2009 proposal snapshot, ${proposalCrosswalkReview.linked} of ${proposalCrosswalkReview.reviewed_proposals} rows (Highwind) is linked to a later final-plan record; ${proposalCrosswalkReview.unresolved} remain blank because similar geography alone is not identity evidence. Empty Crosswalk ID means no reviewed link, not a finding that the projects differ. To investigate a revision, compare Path or scope detail, reported cost, dates, and Change signal. The source locator and URL identify the exact underlying report row.`]];dashboard.getRange("A33").format={fill:C.lavender,font:{color:C.text,size:10},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};

const headers=["Project name","Utility / PTO","Source stream","Project ID (filter this)","Report period","Observation date","Status","Approval year / cycle","Reported cost (nominal $M)","Reported cost dollar year (source / proxy)","Reported cost (selected-year $M)","Initial cost (nominal $M)","Initial cost dollar year (approval-year proxy)","Initial cost (selected-year $M)","Nominal cost change ($M)","Cost change (selected-year $M)","Initial ISD (as written)","Reported ISD (as written)","Schedule shift (years)","Location / route","Path or scope detail","Line length (mi)","Voltage (kV)","Capacity","Change signal","Fields available","Project-level eligibility","Latest utility row?","Source ID","Source locator","Source URL","Source title","Raw reported cost ($000)","Raw initial cost ($000)","Initial ISD date","Reported ISD date","Crosswalk ID (filter this)","Crosswalk method","Crosswalk confidence","Crosswalk evidence"];
title(history,"Project History","Filter Project name and sort Observation date to read its source-reported history. Use Crosswalk ID to link conservatively matched CAISO annual-plan rows across plan years. Price-year and comparison-dollar fields are explained on Dashboard.","AN");history.getRange("A3:AN3").values=[["","","","","","","","","Source-reported cost","Dollar year","","Source-reported cost","Dollar year","","","","","","","","","","","","","","","","","","","","","","","","","","",""]];history.getRange("K3").formulas=[[`="Reported cost ("&Inflation!$G$4&" $M)"`]];history.getRange("N3").formulas=[[`="Initial cost ("&Inflation!$G$4&" $M)"`]];history.getRange("P3").formulas=[[`="Cost change ("&Inflation!$G$4&" $M)"`]];history.getRange("I3:P3").format={fill:C.gold,font:{bold:true,color:C.text,size:9},wrapText:true,horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};history.getRange("I3:P3").format.rowHeight=22;history.getRange("A4:AN4").values=[headers];header(history,"A4:AN4");
const historyData=rows.map(r=>[r.project_name,r.utility,r.stream,r.key,r.period,asDate(r.observation_date),r.status,r.approval,null,null,null,null,null,null,null,null,r.initial_isd,r.reported_isd,null,r.location,r.path,r.length,r.voltage,r.capacity,r.signal,r.available,r.eligibility,r.latest,r.source_id,r.locator,r.url,r.title,r.current_cost_k,r.initial_cost_k,asDate(r.initial_isd_date),asDate(r.reported_isd_date),r.crosswalk_id,r.crosswalk_method,r.crosswalk_confidence,r.crosswalk_evidence]);history.getRange(`A5:AN${end}`).values=historyData;
history.getRange(`I5:I${end}`).formulas=rows.map((_,i)=>[`=IF(ISNUMBER(AG${i+5}),AG${i+5}/1000,"")`]);
history.getRange(`J5:J${end}`).formulas=rows.map((r,i)=>[`=IF(ISNUMBER(I${i+5}),${Number.isInteger(r.reported_cost_year)?r.reported_cost_year:`IF(OR(C${i+5}="Utility TPR",C${i+5}="CAISO annual plan",C${i+5}="CAISO planning report"),YEAR(F${i+5}),"")`},"")`]);
history.getRange(`K5:K${end}`).formulas=rows.map((_,i)=>[`=IF(ISNUMBER(I${i+5}),IF(ISNUMBER(J${i+5}),IFERROR(I${i+5}*INDEX(Inflation!$D$6:$D$29,MATCH(J${i+5},Inflation!$A$6:$A$29,0)),"n.a."),""),"")`]);
history.getRange(`L5:L${end}`).formulas=rows.map((_,i)=>[`=IF(ISNUMBER(AH${i+5}),AH${i+5}/1000,"")`]);
history.getRange(`M5:M${end}`).formulas=rows.map((_,i)=>[`=IF(AND(ISNUMBER(L${i+5}),ISNUMBER(H${i+5})),H${i+5},"")`]);
history.getRange(`N5:N${end}`).formulas=rows.map((_,i)=>[`=IF(ISNUMBER(L${i+5}),IF(ISNUMBER(M${i+5}),IFERROR(L${i+5}*INDEX(Inflation!$D$6:$D$29,MATCH(M${i+5},Inflation!$A$6:$A$29,0)),"n.a."),""),"")`]);
history.getRange(`O5:O${end}`).formulas=rows.map((_,i)=>[`=IF(AND(ISNUMBER(I${i+5}),ISNUMBER(L${i+5})),I${i+5}-L${i+5},"")`]);
history.getRange(`P5:P${end}`).formulas=rows.map((_,i)=>[`=IF(AND(ISNUMBER(K${i+5}),ISNUMBER(N${i+5})),K${i+5}-N${i+5},"")`]);
history.getRange(`S5:S${end}`).formulas=rows.map((_,i)=>[`=IF(AND(ISNUMBER(AI${i+5}),ISNUMBER(AJ${i+5})),(AJ${i+5}-AI${i+5})/365.25,"")`]);
body(history,`A5:AN${end}`);history.getRange(`A5:AN${end}`).format.rowHeight=36;history.getRange(`F5:F${end}`).format.numberFormat="yyyy-mm-dd";history.getRange(`I5:I${end}`).format.numberFormat='"$"#,##0.0';history.getRange(`K5:K${end}`).format.numberFormat='"$"#,##0.0';history.getRange(`L5:L${end}`).format.numberFormat='"$"#,##0.0';history.getRange(`N5:P${end}`).format.numberFormat='"$"#,##0.0';history.getRange(`S5:S${end}`).format.numberFormat="0.0";history.getRange(`V5:V${end}`).format.numberFormat="0.0";history.getRange(`AI5:AJ${end}`).format.numberFormat="yyyy-mm-dd";history.getRange(`AG5:AH${end}`).format.numberFormat="#,##0.0";
for(const [col,width] of [["A",36],["B",13],["C",14],["D",31],["E",18],["F",15],["G",15],["H",18],["I",15],["J",17],["K",20],["L",15],["M",24],["N",20],["O",18],["P",28],["Q",17],["R",18],["S",17],["T",28],["U",64],["V",14],["W",13],["X",14],["Y",40],["Z",43],["AA",24],["AB",17],["AC",24],["AD",28],["AE",60],["AF",48],["AG",19],["AH",18],["AI",16],["AJ",16],["AK",24],["AL",48],["AM",18],["AN",80]])history.getRange(`${col}:${col}`).format.columnWidth=width;
for(const col of ["Z","AF","AG","AH","AI","AJ"])history.getRange(`${col}:${col}`).format.columnWidth=0;
history.getRange(`C5:C${end}`).conditionalFormats.add("containsText",{text:"CAISO",format:{fill:C.lavender}});history.getRange(`AA5:AA${end}`).conditionalFormats.add("containsText",{text:"Review",format:{fill:C.gold,font:{bold:true,color:C.text}}});history.getRange(`AB5:AB${end}`).conditionalFormats.add("containsText",{text:"Yes",format:{fill:C.mint,font:{bold:true,color:C.text}}});history.getRange(`AM5:AM${end}`).conditionalFormats.add("containsText",{text:"High",format:{fill:C.mint,font:{bold:true,color:C.text}}});history.getRange(`K5:K${end}`).conditionalFormats.add("containsText",{text:"n.a.",format:{fill:C.gold,font:{color:C.text}}});history.getRange(`N5:N${end}`).conditionalFormats.add("containsText",{text:"n.a.",format:{fill:C.gold,font:{color:C.text}}});makeTable(history,`A4:AN${end}`,"ProjectHistoryTable");history.freezePanes.freezeColumns(4);

const historic2008=["SRC-CAISO-TPP-2008","CAISO annual plan","PG&E, SCE, SDG&E",new Date("2008-01-28T00:00:00Z"),"2008 CAISO Transmission Plan","https://www.caiso.com/documents/080128briefingon2008transmissionplan-2008plan.pdf","Imported: 178 cited observations from Tables 3-1 to 3-13. Tables 3-1–3 are previously approved status; 3-4–6 are CAISO management-approved proposals; 3-7–9 require Board approval; 3-10 is not approved or still under review; 3-11–13 are short-term-plan recommendations, not approvals. Each row has table, PDF/printed page, and table-row locator; source costs are ranges, upper bounds, lower bounds, or not reported as stated."];
const historic2010_2011=["SRC-CAISO-TPP-2010-2011","CAISO annual plan","PG&E, SCE, SDG&E, IID/SCE",new Date("2011-05-18T00:00:00Z"),"Final ISO 2010/2011 Transmission Plan","https://www.caiso.com/documents/110518decision_transmissionplan-reviseddraftplan.pdf","Imported: 120 cited project rows from Tables 8.1-1, 8.1-2, 8.2-1, and 8.2-2. Tables 8.1-1/2 update expected ISDs for 87 previously approved projects; Table 8.2-1 has cost/ISD for 32 new reliability projects; Table 8.2-2 is one policy project recommended for approval. Table 8.3 candidates are intentionally excluded because they were not found needed in this cycle."];
const historic2011_2012=["SRC-CAISO-TPP-2011-2012","CAISO annual plan","PG&E, SCE, SDG&E",new Date("2012-03-14T00:00:00Z"),"2011/2012 ISO Transmission Plan","https://www.caiso.com/Documents/Decision_2011-12TransmissionPlan-Plan-MAR2012.pdf","Imported: 164 cited project rows from Tables 7.1-1, 7.1-2, and 7.2-1. Tables 7.1-1/2 contain 134 prior-project status/expected-ISD observations (including one cancelled and one replaced entry); Table 7.2-1 contains 30 new reliability projects found needed with cost, service area, and in-service date."];
const laterPlanSources=laterPlans.map(plan=>[plan.data.source.source_id,"CAISO annual plan","CAISO-controlled grid",asDate(plan.date),plan.data.source.source_title,plan.data.source.source_url,`Imported: ${plan.data.records.length} cited project observations from final-plan status tables for previously approved projects and project tables found needed in the ${plan.period} cycle. Every row carries table, PDF page, printed page, and row provenance.`]);
const historic2009=["SRC-CAISO-TPP-2009-LOCATED-UNAVAILABLE","CAISO annual plan","CAISO-controlled grid",new Date("2009-06-01T00:00:00Z"),"2009 California ISO Transmission Plan (amended June 2009)","https://www.caiso.com/2354/2354f34634870.pdf","Located by official contemporaneous citations, but CAISO's current URL returns 404 and no primary-source PDF copy surfaced. No project rows imported. Obtain the final report from CAISO records or another primary repository before extraction."];
const historic2009Proposals=[plan2009Proposals.source.source_id,"CAISO proposal snapshot","2008 Request Window renewable proposals",asDate(plan2009Proposals.source.presentation_date),plan2009Proposals.source.source_title,plan2009Proposals.source.source_url,"Imported: 14 cited proposals from Slides 8–10. These are request-window proposals, not final approvals. Slide 11 says its locations are approximate, not actual routes or detailed configurations, and proposals require further ISO evaluation. No cost is reported."];
const historic2006=["SRC-CAISO-TPP-2006-MEMO","CAISO annual plan","CAISO-controlled grid",new Date("2007-01-18T00:00:00Z"),"2006 CAISO Transmission Plan — Board memorandum","https://www.caiso.com/Documents/2006CAISOTransmissionPlanMemo.pdf","Context anchor. PDF p. 1 states the 2006 plan was the first future annual plan; p. 3 states that specific final-plan projects are CAISO-approved. This memorandum is not a project table."];
const historic2006Excerpt=[plan2006.source.source_id,"CAISO annual plan","PG&E excerpt",asDate(plan2006.source.presentation_date),plan2006.source.source_title,plan2006.source.source_url,"Imported: 12 displayed project rows from the Operating Guide excerpt on PDF p. 10 (slide 10), with exact row citations. This is a partial excerpt, not the complete 2006 plan; cost is not reported."];
const historic2007TehachapiBoard=[plan2007TehachapiBoard.source.source_id,"CAISO Board presentation","Tehachapi / SCE",asDate(plan2007TehachapiBoard.source.report_date),plan2007TehachapiBoard.source.source_title,plan2007TehachapiBoard.source.source_url,"Imported: 15 cited pre-approval observations: one Tehachapi management recommendation and 14 Slide 8 planned facilities. Management recommends Board approval conditioned on FERC consent; the presentation has no project costs, and planned ISDs are not actual completion. This is not a complete 2006 or 2007 annual-plan inventory."];
const historic2007Tehachapi=[plan2007Tehachapi.source.source_id,"CAISO planning report","Tehachapi / SCE",asDate(plan2007Tehachapi.source.report_date),plan2007Tehachapi.source.source_title,plan2007Tehachapi.source.source_url,"Imported: 15 cited partial-baseline observations: one Tehachapi aggregate (the report's $1.8B amount remains unallocated) and 14 Appendix G Table 1 planned facilities with scope, planned in-service date, and size fields where stated. Planned dates are not actual completion. This is not a complete 2007 annual-plan inventory."];
const tehachapiLifecycleSources=tehachapiLifecycle.sources.map(s=>[s.source_id,s.source_stream,"Tehachapi / SCE",asDate(s.report_date),s.source_title,s.source_url,"Imported: project-level Tehachapi lifecycle observations. Source-specific cost bases and statuses are retained; amounts are not cumulative or automatically comparable. See each Project History source locator."]);
const historic2010Briefing=[plan2010Briefing.source.source_id,"CAISO annual plan","SCE, SDG&E",asDate(plan2010Briefing.source.presentation_date),plan2010Briefing.source.source_title,plan2010Briefing.source.source_url,"Imported: 2 individually named Board-approved reliability projects from Slide 7. The briefing’s 29-project / $573M total is aggregate-only and is not allocated to these rows. A public direct URL has not been located; the primary PDF is retained locally in Raw Public Sources."];
const historic2007=["SRC-CAISO-TPP-2007-URL-CORROBORATION","CAISO annual plan","CAISO-controlled grid",new Date("2007-06-15T00:00:00Z"),"CAISO June 15, 2007 rebuttal testimony citing the 2007 Long Term Transmission Plan","https://www.caiso.com/documents/june15_2007rebuttaltestimony-californiaisoinproceedingno_a_06-08-010_sunrisepowerlink.pdf","PDF p. 7, footnote 13 cites the 2007 plan title, January 2007 posting, and original plan URL. The original plan PDF (https://www.caiso.com/1b6b/1b6bb4d51db0.pdf) currently returns 404; no project rows imported."];
const historic2007Catalog=["SRC-CAISO-TPP-2007-FINAL-CATALOG","CAISO annual plan","CAISO-controlled grid",new Date("2007-01-25T00:00:00Z"),"Final 2007 CAISO Transmission Plan — Report — official CAISO catalog record","https://web.archive.org/web/20080517000000id_/http://www1.caiso.com/1ca5/1ca5d8e751ad0.html","Official CAISO catalog lists a 6,815K final report posted Jan. 25, 2007 and says it incorporates Board-recommended naming changes, typo corrections, and latest PTO information. The catalog supports source metadata only: the available archived PDF response is incomplete (125,887 WARC bytes versus its declared 6,815,780 bytes) and is not readable. No project rows imported."];
const bls=["SRC-BLS-CPIU-2025","Inflation reference","U.S. city average",new Date("2026-07-17T00:00:00Z"),"BLS: Year-over-Year Inflation Rate, All Items CPI-U, 2002–2025","https://www.bls.gov/pir/spm/spm_chart_2025data.htm","Imported annual-average CPI-U values, 2013=100. Used only as general-inflation comparison factors."];
const tdfSources=tdf.sources??[tdf.source];
const tdfSourceRows=tdfSources.map(s=>{const observation=tdf.observations.find(r=>r.source_id===s.source_id);return [s.source_id,"CAISO TDF","Multiple PTOs",asDate(s.report_date??s.observation_date??observation?.observation_date),s.source_title,s.source_url,s.source_id===tdf.source.source_id?"Imported. Each Project History row cites the PDF page and table row.":"Imported. Each Project History row cites the source workbook sheet and row."];});
const sourceRows=[...tpr.sources.map(s=>[s.id,"Utility TPR",s.utility,asDate(s.snapshot_date),s.title,s.url,"Imported. Each Project History row cites the source sheet and row."]),...tdfSourceRows,historic2006,historic2006Excerpt,historic2007TehachapiBoard,historic2007Tehachapi,...tehachapiLifecycleSources,historic2010Briefing,historic2007,historic2007Catalog,historic2008,historic2009Proposals,historic2009,historic2010_2011,historic2011_2012,...laterPlanSources,bls];
title(sourceRegistry,"Source Registry","Direct citations for every source stream, including the inflation reference.","G");sourceRegistry.getRange("A4:G4").values=[["Source ID","Source stream","Utility / coverage","Report date","Title","Direct URL","Use / status"]];header(sourceRegistry,"A4:G4");sourceRegistry.getRange(`A5:G${sourceRows.length+4}`).values=sourceRows;body(sourceRegistry,`A5:G${sourceRows.length+4}`);sourceRegistry.getRange(`D5:D${sourceRows.length+4}`).format.numberFormat="yyyy-mm-dd";for(const [col,width]of [["A",25],["B",18],["C",20],["D",15],["E",68],["F",76],["G",65]])sourceRegistry.getRange(`${col}:${col}`).format.columnWidth=width;makeTable(sourceRegistry,`A4:G${sourceRows.length+4}`,"SourceRegistryTable");
title(coverage,"Coverage","An explicit 2005–present map. A gap is missing data, not evidence that nothing changed.","E");coverage.getRange("A4:E4").values=[["Year","Current coverage","What is usable now","Known source / next step","Status"]];header(coverage,"A4:E4");const coverageRows=[];
for(let year=2005;year<=2026;year++){
  let coverage="No project observations imported",usable="Do not infer no change",next="Locate final CAISO plan; record project table, PDF/printed page, and row citation before import",status="Backlog";
  if(year===2005){coverage="Pre-plan: CAISO's new planning process began in summer 2005";usable="Start-year context only; no annual-plan project observation";next="Use predecessor utility/CPUC/FERC records only when a project needs a pre-2006 baseline. Citation: SRC-CAISO-TPP-2006-MEMO, PDF p. 1.";status="Pre-plan";}
  if(year===2006){coverage="First CAISO annual plan: Operating Guide excerpt imported";usable="12 cited PG&E rows: scope, system impact, target ISD, and MVA capacity where stated; no cost. The excerpt is not the full plan.";next="SRC-CAISO-TPP-2006-OPERATING-GUIDE-EXCERPT, PDF p. 10 (slide 10), rows 1–12. Locate the complete plan before using 2006 for totals or crosswalks.";status="Partial";}
  if(year===2007||year===2009||year===2010||year===2011){coverage="Annual CAISO-plan project records not yet imported";usable="Do not use for trend totals yet";next="Locate final plan for this cycle and capture each project table's PDF/printed page and table row. Preserve original cost text, target ISD, scope, and status.";status="Backlog";}
  if(year===2008){coverage="2008 CAISO plan: Tables 3-1 to 3-13 imported";usable="178 cited observations: 85 previously approved-project status rows; 36 CAISO management-approved proposals; 18 Board-required proposals; 3 not-approved or in-review proposals; and 36 short-term-plan recommendations. Recommendation rows retain their needs, recommendation text, and reported status; they are not approval evidence and do not report cost.";next="Tables 3-11–3-13 are now imported. Next: add primary project documents for source-verified costs, routes, scope, and outcomes before treating recommendations as project continuations.";status="Imported";}
  if(year>=2012&&year<=2019){coverage=`${year}-${year+1} CAISO TPP era: final plan project tables not yet imported`;usable="Two-year plan cycle requires a plan-cycle label; do not pretend this is a yearly observation";next="Locate the Board-approved plan for the applicable cycle; extract approval/status tables with project row, PDF/printed page, cost text, ISD, and scope.";status="Backlog";}
  if(year===2020||year===2021){coverage="CAISO TDF annual-plan field for 89 projects";usable="Schedule/status baseline only";next="Add annual CAISO approval-plan project rows";status="Partial";}
  if(year===2022){coverage="CAISO TDF Q1–Q4 for 89 projects";usable="Quarterly schedule/status observations";next="Add cost/path/size evidence from project documents where needed";status="Imported";}
  if(year===2023){coverage="CAISO TDF Q1–Q2 plus October release";usable="Schedule/status observations through October 2023";next="TDF reports do not add cost/path/size fields; add project documents where those fields are needed";status="Imported";}
  if(year===2024){coverage="CAISO TDF January and July; public TPR releases for all three IOUs";usable="TDF schedule/status and TPR project-level cost/path/size fields where reported";next="Add project documents for route, scope, and final cost validation";status="Imported";}
  if(year===2025){coverage="CAISO TDF January and July; public TPR releases for all three IOUs";usable="TDF schedule/status and TPR project-level cost/path/size fields where reported";next="Add project documents for route, scope, and final cost validation";status="Imported";}
  if(year===2026){coverage="CAISO TDF January and July; current TPR: PG&E May, SCE June, SDG&E July";usable="TDF schedule/status and current utility project fields where reported";next="Add later 2026 utility releases when posted";status="Imported";}
  coverageRows.push([year,coverage,usable,next,status]);
}
coverageRows[2010-2005]=[2010,"2010 CAISO plan Board briefing: two named Board-approved reliability projects imported","Two cited project observations (Alberhill Substation Project and Bayfront Substation Project). Slide 7 reports 29 reliability approvals totaling $573M but gives no individual cost, scope, route, or schedule values.","Retain this as partial coverage only. Recover the final 2010 plan or project list before using 2010 for project-count or cost trend totals. The 2010/11 final-plan observation remains separately recorded under 2011.","Partial"];
coverageRows[2011-2005]=[2011,"2010/11 CAISO plan: Tables 8.1-1 to 8.2-2 imported","2011 plan observation: expected ISDs for 87 previously approved projects; cost/ISD for 32 new reliability projects; one policy project recommended for approval","Next: locate the final 2009 plan and extract cited rows; then add a documented project crosswalk before analyzing individual projects across plan years.","Imported"];
coverageRows[2012-2005]=[2012,"2011/12 CAISO plan: Tables 7.1-1, 7.1-2, and 7.2-1 imported","164 cited observations: expected ISD/status for 134 previously approved projects (including one cancelled and one replaced); cost, service area, and ISD for 30 new reliability projects found needed","Adjacent-cycle crosswalk links are documented through 2025/26. Continue the 2006–09 final-plan backlog or obtain primary project documents for cost and route validation.","Imported"];
for(const plan of laterPlans){const endYear=Number(plan.period.slice(5));coverageRows[endYear-2005]=[endYear,`${plan.period} CAISO plan: final project tables imported`,`${plan.data.records.length} cited project observations. The plan-cycle label is retained; status tables track previously approved projects and new-needed tables record cost, service area, and expected ISD where stated.`,`Adjacent-cycle crosswalk links are documented. Use Source Registry and table/page/row locators before interpreting status or cost changes.`,`Imported`];}
coverageRows[2007-2005]=[2007,"Partial Tehachapi pre-approval and plan-baseline snapshots imported; complete 2007 CAISO plan unavailable","30 cited observations across two reports: January Board presentation (one management recommendation plus 14 Slide 8 facilities) and September renewables report (one retrospective Board-approved aggregate plus 14 Appendix G facilities). The same planned facility names/dates appear in both source snapshots; the January source has no cost and neither source establishes actual completion.","SRC-CAISO-CSRTP-2006-TEHACHAPI-BOARD-2007-01-24, Slides 6–11; and SRC-CAISO-RENEW-2007-TEHACHAPI, Appendix G Table 1 (PDF p. 145). Request the complete final Jan. 25, 2007 annual plan before using 2007 as a statewide inventory or total.","Partial"];
coverageRows[2009-2005]=[2009,"2009 request-window proposal snapshot imported; final plan remains unavailable","14 cited proposal rows: name, category/purpose, and proposed online date. They are not final approvals and provide no cost or actual route.","SRC-CAISO-TPP-2009-PROPOSALS, Slides 8–10. Request the final amended June 2009 plan from CAISO records or another primary repository before using 2009 for final-plan totals.","Partial"];
coverageRows[2009-2005]=[2009,"2009 request-window proposal snapshot plus Tehachapi CPUC approval/cost milestone","14 cited proposal rows remain a partial CAISO snapshot. For Tehachapi, the CPUC CPCN supplies a project-level approved route, 173-mile scope, 4,500 MW capability, and $1,784.740M stated total in 2009 dollars.","SRC-CAISO-TPP-2009-PROPOSALS, Slides 8–10; SRC-CPUC-D09-12-044-TRTP4-11-CPCN. Request the final amended June 2009 CAISO plan before using 2009 for statewide final-plan totals.","Partial"];
coverageRows[2013-2005]=[2013,"Tehachapi Segment 8A undergrounding lifecycle milestone","One cited CPUC decision confirms the required Chino Hills undergrounding and denial of rehearing. This is project-specific evidence, not a statewide CAISO plan inventory.","SRC-CPUC-D13-10-076-TRTP8A-REHEARING, PDF pp. 1–3. Locate the complete 2012/13 final CAISO plan before using 2013 for statewide totals.","Partial"];
coverageRows[2014-2005]=[2014,"Tehachapi UG5 cost-cap modification and completion milestones","One cited CPUC decision adds $23M in 2013 dollars for UG5 voltage control. SCE’s timeline separately reports Segment 6 and Segment 7 completion. These are source-specific records, not a statewide plan inventory.","SRC-CPUC-D14-01-005-TRTP-UG5-COST; SRC-SCE-TRTP-PROJECT-TIMELINE-2016. Locate the complete 2013/14 final CAISO plan before using 2014 for statewide totals.","Partial"];
coverageRows[2016-2005]=[2016,"Tehachapi completion/cost lifecycle milestone","SCE reports full TRTP completion and energization in December 2016; its January 2017 filing states TRTP 4–11 was in service and reports a $2,709M estimated actual construction cost in constant 2016 dollars. This cost is SCE-reported, not CPUC-approved.","SRC-SCE-TRTP-PROJECT-TIMELINE-2016; SRC-SCE-TRTP-PFM-2017-01-18. Locate the complete 2015/16 final CAISO plan before using 2016 for statewide totals.","Partial"];
coverageRows[2017-2005]=[2017,"Tehachapi SCE post-construction cost filing","SCE’s cited cost petition reports its $2,709M estimated actual construction cost for TRTP 4–11 in constant 2016 dollars and acknowledges the project was in service as of December 2016. It is not a CPUC-approved cost finding.","SRC-SCE-TRTP-PFM-2017-01-18, PDF pp. 9–10. Locate the complete 2016/17 final CAISO plan before using 2017 for statewide totals.","Partial"];
coverage.getRange("A5:E26").values=coverageRows;body(coverage,"A5:E26");coverage.getRange("A:A").format.columnWidth=12;coverage.getRange("B:B").format.columnWidth=40;coverage.getRange("C:C").format.columnWidth=43;coverage.getRange("D:D").format.columnWidth=58;coverage.getRange("E:E").format.columnWidth=14;coverage.getRange("E5:E26").conditionalFormats.add("containsText",{text:"Backlog",format:{fill:C.coral,font:{bold:true,color:C.text}}});coverage.getRange("E5:E26").conditionalFormats.add("containsText",{text:"Imported",format:{fill:C.mint,font:{bold:true,color:C.text}}});coverage.getRange("E5:E26").conditionalFormats.add("containsText",{text:"Pre-plan",format:{fill:C.gold,font:{bold:true,color:C.text}}});makeTable(coverage,"A4:E26","CoverageTable");

title(inflation,"Inflation","Annual-average CPI-U is a general-inflation comparison baseline. It is not a construction-cost index.","H");inflation.getRange("F4:G4").values=[["Comparison-dollar year",2025]];header(inflation,"F4:G4");inflation.getRange("G4").format={fill:C.gold,font:{bold:true},horizontalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};inflation.getRange("G4").dataValidation={rule:{type:"list",formula1:"=$A$6:$A$29"}};
inflation.getRange("A4:D4").values=[["Year","CPI-U annual average (2013=100)","Annual CPI-U change","Factor to comparison dollars"]];header(inflation,"A4:D4");inflation.getRange("A6:B29").values=cpi;inflation.getRange("A30:B30").values=[[2026,null]];inflation.getRange("E30:H30").merge();inflation.getRange("E30").values=[["Full-year 2026 CPI-U is not available. 2026 project costs remain nominal in Project History."]];inflation.getRange("E30").format={fill:C.gold,font:{color:C.text,italic:true},wrapText:true};inflation.getRange("C6:C29").formulas=cpi.map((_,i)=>[i===0?"":`=IF(AND(ISNUMBER(B${i+6}),ISNUMBER(B${i+5})),B${i+6}/B${i+5}-1,"")`]);inflation.getRange("D6:D29").formulas=cpi.map((_,i)=>[`=IF(ISNUMBER(B${i+6}),INDEX($B$6:$B$29,MATCH($G$4,$A$6:$A$29,0))/B${i+6},"")`]);body(inflation,"A6:D30");inflation.getRange("B6:B29").format.numberFormat="0.000";inflation.getRange("C6:C29").format.numberFormat="0.0%";inflation.getRange("D6:D29").format.numberFormat="0.0000";inflation.getRange("A:A").format.columnWidth=14;inflation.getRange("B:B").format.columnWidth=31;inflation.getRange("C:C").format.columnWidth=20;inflation.getRange("D:D").format.columnWidth=28;inflation.getRange("E:E").format.columnWidth=20;inflation.getRange("F:F").format.columnWidth=26;inflation.getRange("G:G").format.columnWidth=18;inflation.getRange("H:H").format.columnWidth=20;
inflation.getRange("A33:H33").merge();inflation.getRange("A33").values=[["How Project History uses this table"]];inflation.getRange("A33").format={fill:C.teal,font:{bold:true,color:C.white,size:11}};inflation.getRange("A34:H37").merge();inflation.getRange("A34").values=[["Reported cost dollar year uses the source’s stated dollar year when available; otherwise the Utility TPR, CAISO annual-plan, or CAISO planning-report year is used as a proxy. Initial cost dollar year uses the CAISO approval year when present and is labeled as a proxy. For CAISO plan cost ranges, the displayed value is a midpoint; for '<' values, it is the stated ceiling. The 2007 Tehachapi $1.8B is a source-reported aggregate, not allocated to component facilities. Project History keeps each cost's Source ID, source locator, and URL alongside the cost field. Changing the comparison-dollar year in G4 changes both calculated values and calculated-cost column titles. A result of “n.a.” means the price year is outside the annual CPI-U reference or the full-year index is not available. BLS source: https://www.bls.gov/pir/spm/spm_chart_2025data.htm"]];inflation.getRange("A34").format={fill:C.mint,font:{color:C.text,size:10},wrapText:true,verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:C.line}};inflation.freezePanes.freezeRows(4);

for(const sheet of [dashboard,history,sourceRegistry,coverage,inflation]){const used=sheet.getUsedRange();if(used)used.format.verticalAlignment="top";}wb.recalculate();await fs.mkdir("/Users/nicoleshi/Documents/Codex/CA Transmission Data/i-w/outputs",{recursive:true});const file=await SpreadsheetFile.exportXlsx(wb);await file.save(out);console.log(JSON.stringify({out,observations:rows.length,sources:sourceRows.length,cpiYears:cpi.length}));
